apiVersion: v1
kind: ConfigMap
metadata:
  name: phoenixcoder-config
  namespace: phoenixcoder
data:
  # PostgreSQL配置（使用已安装的PostgreSQL服务）
  POSTGRES_HOST: "postgresql.default.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "phoenixcoder"
  POSTGRES_USER: "postgres"
  
  # Redis配置（使用已安装的Redis服务）
  REDIS_HOST: "redis-master.default.svc.cluster.local"
  REDIS_PORT: "6379"
  
  # OIDC服务配置
  OIDC_ISSUER: "http://community-oidc-server.phoenixcoder.svc.cluster.local:8000"
  OIDC_CLIENT_ID: "phoenixcoder-client"
  OIDC_REDIRECT_URI: "http://community-admin.phoenixcoder.svc.cluster.local/auth/callback"
  
  # JWT配置
  # 警告：请使用强随机密钥，建议使用 security/generate-keys.sh 生成
  JWT_SECRET: "your_jwt_secret_key_here_at_least_32_characters"
  
  # 应用环境
  APP_ENV: "development"
  DEBUG: "true"
  
  # 前端配置
  REACT_APP_API_URL: "http://community-server.phoenixcoder.svc.cluster.local:8000"
  REACT_APP_OIDC_ISSUER: "http://community-oidc-server.phoenixcoder.svc.cluster.local:8000"
  REACT_APP_CLIENT_ID: "community-admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: phoenixcoder-secrets
  namespace: phoenixcoder
type: Opaque
data:
  # 警告：请使用强密码和密钥，建议使用 security/generate-keys.sh 生成
  # 以下是占位符，请替换为实际的 Base64 编码值
  # 使用命令生成：echo -n "your_password" | base64
  POSTGRES_PASSWORD: eW91cl9zdHJvbmdfcG9zdGdyZXNfcGFzc3dvcmRfaGVyZQ==  # your_strong_postgres_password_here
  REDIS_PASSWORD: eW91cl9yZWRpc19wYXNzd29yZF9oZXJl  # your_redis_password_here
  OIDC_CLIENT_SECRET: eW91cl9vaWRjX2NsaWVudF9zZWNyZXRfaGVyZV9hdF9sZWFzdF8zMl9jaGFyYWN0ZXJz  # your_oidc_client_secret_here_at_least_32_characters