# 注意：这是密钥配置模板，实际部署时需要替换为真实的密钥值
# 建议使用 kubectl create secret 命令或外部密钥管理系统

apiVersion: v1
kind: Secret
metadata:
  name: phoenixcoder-secrets
  namespace: staging
  labels:
    app: phoenixcoder
    environment: staging
type: Opaque
data:
  # 数据库连接字符串 (base64编码)
  # 示例: postgresql://user:password@host:5432/dbname
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAaG9zdDo1NDMyL2RibmFtZQ==
  
  # Redis连接字符串 (base64编码)
  # 示例: redis://localhost:6379/0
  redis-url: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OS8w
  
  # JWT密钥 (base64编码)
  # 生成方法: openssl rand -base64 32
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWtleS1oZXJl
  
  # OIDC客户端密钥 (base64编码)
  oidc-client-secret: eW91ci1vaWRjLWNsaWVudC1zZWNyZXQ=
  
  # 邮件服务密码 (base64编码)
  smtp-password: eW91ci1zbXRwLXBhc3N3b3Jk
  
  # 微信小程序密钥 (base64编码)
  wechat-app-secret: eW91ci13ZWNoYXQtYXBwLXNlY3JldA==
  
  # 文件存储密钥 (base64编码)
  storage-access-key: eW91ci1zdG9yYWdlLWFjY2Vzcy1rZXk=
  storage-secret-key: eW91ci1zdG9yYWdlLXNlY3JldC1rZXk=
---
# TLS证书密钥（由cert-manager自动管理）
apiVersion: v1
kind: Secret
metadata:
  name: staging-api-tls
  namespace: staging
type: kubernetes.io/tls
# data:
#   tls.crt: <base64-encoded-certificate>
#   tls.key: <base64-encoded-private-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: staging-oidc-tls
  namespace: staging
type: kubernetes.io/tls
# data:
#   tls.crt: <base64-encoded-certificate>
#   tls.key: <base64-encoded-private-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: staging-admin-tls
  namespace: staging
type: kubernetes.io/tls
# data:
#   tls.crt: <base64-encoded-certificate>
#   tls.key: <base64-encoded-private-key>