export default {
    pages: [
        'pages/task-hall/index',
        'pages/login/index',
        'pages/register/index',
        'pages/growth/index',
        'pages/growth/pathDetail',
        'pages/growth/challengeDetail',
        'pages/knowledge-helper/index',
        'pages/club/index',
        'pages/profile/index',
        'pages/problem/index',
        'pages/post/index',
        'pages/post/Detail',
        'pages/post/Publish',
    ],
    window: {
        backgroundTextStyle: 'dark',
        navigationBarBackgroundColor: '#1E1E2F',
        navigationBarTitleText: 'PhoenixCoder',
        navigationBarTextStyle: 'white',
    },
    debug: true,
    tabBar: {
        position: 'bottom',
        borderStyle: 'black',
        color: '#A0A0A0',
        selectedColor: '#3D5AFE',
        backgroundColor: '#1E1E2F',
        list: [
            {
                pagePath: 'pages/task-hall/index',
                text: '任务大厅',
                iconPath: './assets/images/index.png',
                selectedIconPath: './assets/images/index_focus.png',
            },
            {
                pagePath: 'pages/growth/index',
                text: '成长路线',
                iconPath: './assets/images/discovery.png',
                selectedIconPath: './assets/images/discovery_focus.png',
            },
            {
                pagePath: 'pages/knowledge-helper/index',
                text: '知识助手',
                iconPath: './assets/images/index.png',
                selectedIconPath: './assets/images/index_focus.png',
            },
            {
                pagePath: 'pages/club/index',
                text: '社区互动',
                iconPath: './assets/images/discovery.png',
                selectedIconPath: './assets/images/discovery_focus.png',
            },
            {
                pagePath: 'pages/profile/index',
                text: '我的',
                iconPath: './assets/images/burger.png',
                selectedIconPath: './assets/images/burger_focus.png',
            },
        ],
    },
    sitemapLocation: 'sitemap.json',
};
