apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-admin
  namespace: phoenixcoder
  labels:
    app: community-admin
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community-admin
  template:
    metadata:
      labels:
        app: community-admin
        component: frontend
    spec:
      containers:
      - name: admin
        image: localhost:32000/community-admin:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: phoenixcoder-config
              key: REACT_APP_API_URL
        - name: REACT_APP_OIDC_ISSUER
          valueFrom:
            configMapKeyRef:
              name: phoenixcoder-config
              key: REACT_APP_OIDC_ISSUER
        - name: REACT_APP_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: phoenixcoder-config
              key: REACT_APP_CLIENT_ID
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      restartPolicy: Always